### PR TITLE
Adding features, not very clean though sorry

### PR DESCRIPTION
**Pull request by interrogator**
* print cool info to console
* do not require start/end --- figure this out by seeing if start already filled
* fill final column using time delta
* default use of username to get worksheet
* you can create a `.config.json` that stores the spreadsheet id and path to credentials if you like, or supply on command line

### CODE REVIEW

**Comment by hukkin** [comment]
Shamelessly already copied the one feature from here that I wanted: `do not require start/end --- figure this out by seeing if start already filled`. Thanks for that! The dope prints and other features I don't really need, so not merging. Btw note that the feature `fill final column using time delta` is not needed, since the value in this column is automatically updated by the spreadsheet.

**Comment by interrogator** [comment]
Then you are lost. I will maintain my own fork.

**Comment by hukkin** [comment]
Haha, let's see which one gets more stars ;)

**Comment by interrogator** [comment]
Fork loggo.

**Comment by hukkin** [comment]
Already did: https://github.com/hukkinj1/loggo

**Pull request closed without merging**
